version: '3.9'
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=ngods
      - POSTGRES_USER=ngods
      - POSTGRES_DB=ngods
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ngods"]
      interval: 5s
      timeout: 5s
      retries: 5

  metastore:
    build: metastore/
    container_name: metastore
    ports:
      - '9083:9083' # Metastore thrift
    depends_on:
      postgres:
        condition: service_healthy
  trino:
    image: trinodb/trino:425
    container_name: trino
    volumes:
      - ./trino/catalog:/etc/trino/catalog
      - ./trino/log.properties:/etc/trino/log.properties
    ports:
      - '8060:8080'
    depends_on:
      postgres:
        condition: service_healthy
